"""empty message

Revision ID: 2a2d997b3a7c
Revises: 8c4988c0836b
Create Date: 2023-10-17 10:16:24.494552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a2d997b3a7c"
down_revision = "8c4988c0836b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pull_request", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_pull_request_user_id_user"), "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pull_request", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_pull_request_user_id_user"), type_="foreignkey"
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
