"""empty message

Revision ID: 340c49be93ec
Revises: e565f5e6539d
Create Date: 2023-10-17 10:37:08.624030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "340c49be93ec"
down_revision = "e565f5e6539d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pr_commit_association",
        sa.Column("pull_request_number", sa.Integer(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commit_sha"],
            ["commit.sha"],
            name=op.f("fk_pr_commit_association_commit_sha_commit"),
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_number"],
            ["pull_request.number"],
            name=op.f("fk_pr_commit_association_pull_request_number_pull_request"),
        ),
        sa.PrimaryKeyConstraint(
            "pull_request_number", "commit_sha", name=op.f("pk_pr_commit_association")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pr_commit_association")
    # ### end Alembic commands ###
