"""empty message

Revision ID: 478cd764b542
Revises: 340c49be93ec
Create Date: 2023-10-17 13:45:16.712834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478cd764b542'
down_revision = '340c49be93ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_repo_html_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('head_repo_clone_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('base_repo_html_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('base_repo_clone_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_request', schema=None) as batch_op:
        batch_op.drop_column('base_repo_clone_url')
        batch_op.drop_column('base_repo_html_url')
        batch_op.drop_column('head_repo_clone_url')
        batch_op.drop_column('head_repo_html_url')

    # ### end Alembic commands ###
