"""empty message

Revision ID: 492d08571cd8
Revises: 
Create Date: 2023-08-31 11:35:28.992760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492d08571cd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('commit',
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('committer_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('committed_date', sa.DateTime(), nullable=False),
    sa.Column('authored_date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('revert', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['committer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sha')
    )
    op.create_table('patch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_sha'], ['commit.sha'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('source_sha', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('web_url', sa.String(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_sha'], ['commit.sha'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iid')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('allow_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('web_url', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('pipeline')
    op.drop_table('patch')
    op.drop_table('commit')
    op.drop_table('user')
    # ### end Alembic commands ###
