"""empty message

Revision ID: 68f1549ad9aa
Revises: dd528d904ea8
Create Date: 2023-10-25 15:08:19.500066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "68f1549ad9aa"
down_revision = "dd528d904ea8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "key_value",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_key_value")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("key_value")
    # ### end Alembic commands ###
