"""empty message

Revision ID: 6b47df420867
Revises: 
Create Date: 2023-10-16 18:34:41.192811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b47df420867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('login', name=op.f('uq_user_login'))
    )
    op.create_table('commit',
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('committer_id', sa.Integer(), nullable=True),
    sa.Column('commit_author', sa.String(), nullable=False),
    sa.Column('commit_committer', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('committed_date', sa.DateTime(), nullable=False),
    sa.Column('authored_date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('revert', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_commit_author_id_user')),
    sa.ForeignKeyConstraint(['committer_id'], ['user.id'], name=op.f('fk_commit_committer_id_user')),
    sa.PrimaryKeyConstraint('sha', name=op.f('pk_commit'))
    )
    op.create_table('patch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commit_sha'], ['commit.sha'], name=op.f('fk_patch_commit_sha_commit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patch'))
    )
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('source_sha', sa.String(length=40), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('web_url', sa.String(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['source_sha'], ['commit.sha'], name=op.f('fk_pipeline_source_sha_commit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline')),
    sa.UniqueConstraint('iid', name=op.f('uq_pipeline_iid'))
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('allow_failure', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('web_url', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], name=op.f('fk_job_pipeline_id_pipeline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    op.drop_table('pipeline')
    op.drop_table('patch')
    op.drop_table('commit')
    op.drop_table('user')
    # ### end Alembic commands ###
