"""empty message

Revision ID: cbaa6f375fcc
Revises: 
Create Date: 2023-08-30 19:42:16.728870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaa6f375fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('commit',
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('committer_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('committed_date', sa.DateTime(), nullable=False),
    sa.Column('authored_date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['committer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('sha')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commit')
    op.drop_table('user')
    # ### end Alembic commands ###
